routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Admin\UserController;

use App\Http\Controllers\ContactUsFormController;
// use ProfileController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('/profile', ProfileController::class);

// Route::resource('/courses', CourseController::class);


// ADMIN ROUTES
Route::prefix('admin')->name('admin.')->middleware(['auth', 'auth.isAdmin', 'verified'])->group(function () {
    Route::resource('/users', UserController::class);
    Route::resource('/courses', CourseController::class);
});

Route::get('/contact', [ContactUsFormController::class, 'createForm']);

Route::post('/contact', [ContactUsFormController::class, 'ContactUsForm'])->name('contact.store');

// USER ROUTES
// Route::prefix('user')->name('user.')->middleware(['auth', 'auth'])->group(function () {
//     Route::resource('/profile', UserController::class);
// });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Hash;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    // public function setPasswordAttribute($password)
    // {
    //     $this->attributes['password'] = Hash::make($password);
    // }

    public function roles()
    {
        return $this->belongsToMany('App\Models\Role');
    }

    public function courses()
    {
        return $this->belongsToMany('App\Models\Course');
    }
    /**
     *  check if user has a role
     * @param string $role
     * @return bool
     */
    public function hasAnyRole(string $role)
    {
        return null !== $this->roles()->where('name', $role)->first();
    }

    /**
     *  check if user has any given role
     * @param array $roles
     * @return bool
     */
    public function hasAnyRoles(array $roles)
    {
        return null !== $this->roles()->whereIn('name', $roles)->first();
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Actions\Fortify\CreateNewUser;
use App\Http\Requests\StoreUserRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Password;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        // $users = User::all();
        // return view('admin.users.index')
        //     ->with([
        //         'users' => User::all()
        //     ]);
        // return view('admin.users.index', ['users' => User::all()]);
        if(Gate::denies('logged-in')){
            dd("logeate gato");
        }
        if(Gate::allows('is-admin')) {
            return view('admin.users.index', ['users' => User::paginate(10)]);
        }
        dd('only admin');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create', ['roles' => Role::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserRequest $request)
    {
        //dd($request);
        // $validatedData = $request->validated();
        // $user = User::create($validatedData);
        // $user = User::create($request->except(['_token', 'roles']));
        $newUser = new CreateNewUser();
        $user = $newUser->create($request->only(['name', 'email', 'password', 'password_confirmation']));
        $user->roles()->sync($request->roles);

        Password::sendResetLink($request->only(['email']));

        $request->session()->flash('success', 'You hava created the user');

        return redirect(route('admin.users.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.users.edit',
            [
                'user' => User::find($id),
                'roles' => Role::all()
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $user = User::findOrFail($id);
       if (!$user)
       {
           $request->session()->flash('error', 'You can no edit this user.');
           return redirect(route('admin.users.index'));
       }
       $user->update($request->except(['_token', 'roles']));
       $user->roles()->sync($request->roles);
       $request->session()->flash('success', 'You hava edited the user');

       return redirect(route('admin.users.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        //dd($id);
        User::destroy($id);
        $request->session()->flash('success', 'You hava deleted the user');
        return redirect(route('admin.users.index'));
    }
}

resources/views/admin/users/create.blade.php
@extends('templates.main', ['activePage' => 'users', 'title' => __('Nuevo usuario de usuario')])

@section('content')
<div class="content">
    <div class="block-header">
        <h2>Crear perfiles de Usuarios</h2>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <form action="{{ route('admin.users.store') }}" method="POST">
                @include('admin.users.partials.form', ['create' => true])
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('templates.main')

@section('content')
<h2>edit user</h2>
<form action="{{ route('admin.users.update', $user->id) }}" method="POST">
    @method('PATCH')
    @include('admin.users.partials.form')
</form>
@endsection

resources/views/admin/users/index.blade.php
@extends('templates.main', ['class' => 'off-canvas-sidebar', 'activePage' => 'user-index', 'title' => __('Administracion de Usuarios')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="float-left">Administracion de <strong>usuarios</strong></h2>
                    <a class="btn btn-sm btn-primary float-right padding-3" href="{{route('admin.users.create')}}" role="button">Create</a>
                </div>
            </div>
            {{-- <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#Id</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Correo Electronico</th>
                    <th scope="col">Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                <tr>
                <th scope="row">{{$user->id}}</th>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="{{route('admin.users.edit', $user->id)}}" role="button">Update</a>

                        <button type="button" class="btn btn-sm btn-danger"
                            onclick="event.preventDefault();
                            document.getElementById('delete-user-form-{{$user->id}}').submit()">
                            Delete
                        </button>
                        <form id="delete-user-form-{{$user->id}}" action="{{route('admin.users.destroy', $user->id)}}" method="POST" style="display: none;">
                            @csrf
                            @method("DELETE")

                        </form>
                    </td>
                </tr>
                @endforeach
                </tbody>
            </table>
            {{$users->links()}} --}}
            <div class="card card-nav-tabs">
                <div class="card-header card-header-primary">
                  <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
                  <div class="nav-tabs-navigation">
                    <div class="nav-tabs-wrapper">
                      <ul class="nav nav-tabs" data-tabs="tabs">
                        <li class="nav-item">
                          <a class="nav-link active show" href="#admin" data-toggle="tab">
                            <i class="fas fa-user-shield fa-2x"></i> Administrador
                          </a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#teacher" data-toggle="tab">
                            <i class="fas fa-chalkboard-teacher fa-2x"></i> Profesor
                          <div class="ripple-container"></div></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#student" data-toggle="tab">
                            <i class="fas fa-user-graduate fa-2x"></i> Alumno
                          <div class="ripple-container"></div></a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="card-body ">
                    <div class="tab-content text-center">
                        <div class="tab-pane active show" id="admin">
                            @include('admin.users.partials.table', ['adminTable' => true])
                        </div>
                        <div class="tab-pane" id="teacher">
                            @include('admin.users.partials.table', ['teacherTable' => true])
                        </div>
                        <div class="tab-pane" id="student">
                            @include('admin.users.partials.table', ['studentTable' => true])
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection